### PR TITLE
Enable error reporting

### LINKED ISSUE #509: Add an error reporter
This feature would be to alert developers to any errors in Begiak.
If it encountered an error, it would first put the error message in the pastebin. Then, it would put a link as a comment on an issue called "Begiak errors" or something.

### PR DESCRIPTION
**Pull request by scoopgracie**
Closes #509. This is my proposal for an error reporting system. See the updated readme for details.

See http://scoopgracie.com:8080/ for a demo of the log access UI. Username is admin; password is password. Sorry if it goes down.

### CODE REVIEW

**Comment by dolphingarlic** [comment]
This looks pretty solid. Is it possible to style the error logging page as well?

**Comment by scoopgracie** [comment]
Sure, I could add CSS. Just figured it didn't need it, but I could easily
do it.

**Comment by Androbin** [comment]
@wei2912 Friendly ping.

**Comment by scoopgracie** [comment]
OK, this is ready to accept.

**Pull request closed without merging**
