### PR TITLE
Provide dedicated methods for protocol messages

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by sushain97** [comment]
What about putting these inside `irc.py` itself? They are effectively instance methods.

**Comment by Androbin** [comment]
> What about putting these inside `irc.py` itself?

The rationale was to separate connection handling etc. from the higher protocol.

> They are effectively instance methods.

Yeah, how about referencing them, similar to the `PhennyWrapper` objects (`bot.py`)?

**Comment by Androbin** [comment]
> They are effectively instance methods.

Good point, I instead linked them via `__getattr__`, similar to the `PhennyWrapper` objects.

**Comment by sushain97** [comment]
Okay it looks better now but single underscore methods conventionally indicate private members and that isn't really accurate here.

**Comment by Androbin** [comment]
Yeah, but `phenny.nick` is already taken and `phenny.pass` is not valid (keyword).

**Comment by sushain97** [comment]
Maybe we should do something like `self.proto.nick`, etc. then? for `pass`, I understand using the underscore.

**Comment by sushain97** [comment]
Sounds good to me.

**Pull request merged**
