### PR TITLE
Be more reserved about .more

### PR DESCRIPTION
**Pull request by Androbin**
Proposal for #410

### CODE REVIEW

**Comment by Androbin** [comment]
**Old behavior:** For each call, print the first message and queue the rest.
**Problem:** It does so, even when there are already queue messages.

**New behavior:** Always queue new messages and print number of queued messages & tag.
[ Alternative: Queue, if there are queued messages. Print number of queued messages & tag. ]

**Comment by jonorthwash** [comment]
How long does it wait before unqueuing?

**Comment by Androbin** [comment]
Currently: as soon as someone says `.more [N] [tag]`
[ Alternative: Queue and automatically print in batches ]

**Comment by jonorthwash** [comment]
So it queues infinitely until someone happens to say `.more`, and then it floods the channel until the [now very large] queue is empty?  That doesn't sound like what we want...

**Comment by Androbin** [comment]
By default, it prints the next message. You can also specify the number of messages to unqueue.

**Comment by jonorthwash** [comment]
I don't get how it behaves though.  Does it just infinitely queue, always needing `.more` to get the next thing in the queue?  If you get 50 messages per day, and type `.more` once every two days, the queue just grows indefinitely....

**Comment by Androbin** [comment]
See https://github.com/apertium/phenny/pull/408#issuecomment-373939211 for reference.
The current behavior is to only queue when multiple messages are generated at once.
But since that didn't work for e.g. the git hook, we need to rethink this.

We could generate less messages to begin with.
But we can't print less messages/hour without dropping some.

**Comment by sushain97** [comment]
I don't think .more is necessarily the correct way to do this.

Instead, we need a debounce decorator with wait=5s. Then, we use that debounced function in git instead of normal msg. The debounce decorator will only execute a function call after it hasn't received one for 5s and it will by default execute the trailing edge (final call) unless the decorator also comes with a callback that accepts all the messages and produces one message to replace them. .git would implement this callback.

There's almost certainly a Python debounce implementation floating out there.

**Comment by jonorthwash** [comment]
> The current behavior is to only queue when multiple messages are generated at once.

I'm not talking about things that come all at once.  The issue I opened was for something different.

**Comment by sushain97** [comment]
We could also throttle instead of debounce.

for the uninitiated: https://stackoverflow.com/questions/25991367/difference-between-throttling-and-debouncing-a-function

**Comment by Androbin** [comment]
Why not add `debounce` functionality to `more` infrastructure?
We can use a callback to re-compute messages for the respective tag.

**Comment by sushain97** [comment]
We could but they seem orthogonal. .more is meant to hold messages and debounce/throttle will more or less throw away messages.

**Comment by Androbin** [comment]
Let's continue this discussion in the respective tickets.
git hook behavior: #407
.more behavior: #410
debounce behavior: #411

**Comment by Androbin** [comment]
See https://github.com/apertium/phenny/issues/410#issuecomment-373948504

**Comment by wei2912** [comment]
@Androbin Just wondering, why are the PRs open when the issue is closed? Would they still be of relevance?

**Comment by Androbin** [comment]
@wei2919 See the above two comments.
This solution was abandoned and two new issues were created.
All three issues (including the original) are still relevant.

**Pull request closed without merging**
