### PR TITLE
Pass command args properly

### LINKED ISSUE #427: Begiak should greet people after n seconds
Begiak should greet people after n seconds, where n is longer than it takes for Brainstorm to kick spammers

```
* strugee3 (~strugee@2402:800:6127:5145:a05f:e28b:8c6c:f179) has joined
<begiak> Welcome to #apertium, strugee3!  Stick around for a while and someone will address any questions you have :)
<strugee3> LRH OFFICIAL: We are not spamming you | https://www.youtube.com/watch?v=
* Brainstorm has kicked strugee3 from #apertium (Please ignore the spam)
```

Should be:

```
* strugee3 (~strugee@2402:800:6127:5145:a05f:e28b:8c6c:f179) has joined
<strugee3> LRH OFFICIAL: We are not spamming you | https://www.youtube.com/watch?v=
* Brainstorm has kicked strugee3 from #apertium (Please ignore the spam)
```

### PR DESCRIPTION
**Pull request by Androbin**
Towards #427 
See #429

### CODE REVIEW

**Comment by Androbin** [comment]
@ftyers I just realized, the `kicked` command shouldn't use `phenny.nick` but the name of the kicked user which we don't currently pass to commands.

**Comment by LuccoJ** [comment]
I think this should probably be done more generically, as there are two issues I see with it:

* only kicked users are considered, and not users who spontaneously part after just a second or two (which does happen, for a variety of reasons);
* the "kicked" set will grow indefinitely until the bot is restarted.

I think a better solution would be to keep a set of "present" users, i.e. users who have JOINed the channel but not PARTed it, QUIT, or been KICKed. In other words, there would need to be a command that reacts to JOIN by adding the user to a set, and then commands that react to QUIT, PART and KICK by removing the user from the same set. That way, the set will always include users who are on the channel, which is also more generally useful for any future perspective.

**Comment by Androbin** [comment]
Also, I think we're not passing the IRC message `args` properly.

**Comment by LuccoJ** [comment]
I've pushed a version of this that does it the way I described, plus using input.group() instead of input.args since you say that may not work correctly... but I don't know if input.group() does, and I am not able to test this on my bot, so please just take it as an indication of the things I think should be addressed.
I also don't know whether I've done the PR properly, or I should have somehow branched from _this_ one instead... sorry, I don't often use Git or GitHub.

**Pull request merged**
