### PR TITLE
Module cleaning

### PR DESCRIPTION
**Pull request by nu11us**
Referencing issue #436
- **lastfm**: very rarely used. 
    - Couldn't find it being used within the last few years of logs.
- **tfw**: obsolete due to weather command / slightly NSFW
- **rule34**: NSFW
- **fcc**: unused
- **foodforus**: unused
- **mylife**: unused
- **vtluug**: unused
- **wuvt**: unused

### CODE REVIEW

**Comment by Androbin** [comment]
Don't forget to remove the respective test modules.

**Comment by Androbin** [comment]
> Couldn't find it being used within the last few years of logs.

Did you do this for (all) other modules as well?
If not, this could probably be automated.

**Comment by wei2912** [comment]
Do take note that removal of the modules will require changes to the other files; take a look at the Travis CI build for more details. (You may wish to give Begiak a test on another channel.)

On another note, a few other module like `archwiki` and `fcc` are very rarely used. If you're familiar with the Linux command line, you may wish to do a grep of all messages starting with `.` in the log (look into grep's regex syntax) and identify the most commonly used modules. It'd be great if you could have a list commands along with the frequency of use over the last few years. That way, we can easily identify rarely use modules. At the same time, you can test out rarely used modules to check if they still work.

Let me know your findings before proceeding with the changes.

**Comment by nu11us** [comment]
> > Couldn't find it being used within the last few years of logs.
> 
> Did you do this for (all) other modules as well?
> If not, this could probably be automated.

Yeah, I wrote a python script after downloading the logs from @TinoDidriksen 's database. After this task, I can work on automating it.



> Do take note that removal of the modules will require changes to the other files; take a look at the Travis CI build for more details. (You may wish to give Begiak a test on another channel.)
> 
> On another note, a few other module like `archwiki` and `fcc` are very rarely used. If you're familiar with the Linux command line, you may wish to do a grep of all messages starting with `.` in the log (look into grep's regex syntax) and identify the most commonly used modules. It'd be great if you could have a list commands along with the frequency of use over the last few years. That way, we can easily identify rarely use modules. At the same time, you can test out rarely used modules to check if they still work.
> 
> Let me know your findings before proceeding with the changes.

I used python instead of command line, but the issue I came into with all messages starting with '.' was that file extensions and the link were being included as well. The easier implementation was to have a function that finds the occasion of each command, and if needed one could iterate through all the installed commands/modules.

**Comment by shardulc** [comment]
`apertium_chill.py` and `chillmeter.py` seem to be duplicates, can you look into it (and check if there are any others)? Also, I think a large number of other modules are also not used, such as `slogan.py`, `stache.py`, ... if you can tell us about usage frequency for those then we could make a decision about deleting them.

**Comment by nu11us** [comment]
https://pastebin.com/15sjKs93

**Comment by nu11us** [comment]
Includes some obvious false-positives, but it shows the stats nonetheless.

**Comment by nu11us** [comment]
I've posted it in the issue #436 .

**Comment by nu11us** [comment]
Chill/Chillmeter hasn't been used in around 6 months.

**Comment by nu11us** [comment]
Ready to merge? #442 is waiting on this PR.

**Comment by wei2912** [comment]
I'll merge this PR for now, as none of the changes here should cause significant issues with the bot.

**Pull request merged**
