### PR TITLE
Refactor/Fix Wikipedia modules

### PR DESCRIPTION
**Pull request by Androbin**
The various Wiki modules were doing quoting / formatting / snippet extraction inconsistently.
* Unifies code (removes noise) & Fixes behavior
* Makes snippet extraction more robust
* Adds section support to the rest of Wiki modules
* Fixes currently failing tests and adds ^-- new

### CODE REVIEW

**Comment by Androbin** [comment]
@shardulc Just in case: Have I missed some edge case or can we merge this?

**Comment by shardulc** [comment]
Hi, sorry, but is it fine if I take a look tomorrow?

**Comment by Androbin** [comment]
Sure, we got time.

**Comment by Androbin** [comment]
I have already thoroughly tested it.
I just wanted some feedback on the code.

**Comment by Androbin** [comment]
@shardulc Still awaiting review...

**Comment by Androbin** [comment]
I have already thoroughly tested it by now.
If there is no objection by tomorrow or so, I will proceed.

**Comment by sushain97** [comment]
It is just me or do the tests not actually verify that the extracted content is more or less accurate and instead just check if the extracted content is a subset of the original page? If so, we need something a bit better. Perhaps checks on the length of the returned text and checks that the correct section has been extracted?

**Comment by Androbin** [comment]
@sushain97 Yeah, the current tests don't do a good job in that respect.
Actually, such tests would have caught some of the bugs fixed in this PR.
Although it should be much more robust now, some more in-depth tests would be good.
I will compose additional tests which check a list of extracts for certain keywords.

**Pull request merged**
