### PR TITLE
fixed case-sensitive command problem

### PR DESCRIPTION
**Pull request by n3rsti**
Added lowercase to text in CommandInput class and parsed text to string in case text wouldn't be String.
I had lag and i don't know if my previous pull request was sent.

### CODE REVIEW

**Comment by wei2912** [comment]
https://github.com/apertium/phenny/issues/488

I saw that this was also addressed in https://github.com/apertium/phenny/pull/497, and I prefer the solution of having the regex ignore case by default, rather than enforcing lower case across all commands. Nevertheless, will leave this PR open for now.

**Comment by scoopgracie** [comment]
The advantage of this is that it works with all commands, including ones like tell that don't work with mine.

**Comment by Androbin** [comment]
Wouldn't this change lowercase all and any payload text?
The case can be very important, for example:
We have modules that recognize URLs (which don't work when lowercased).
We have commands that store and/or send text to someone (which shouldn't modify the text).
We have commands that work with usernames or other identifier that are case-sensitive.

**Comment by Androbin** [comment]
The entirety of this project doesn't differentiate between parts of the regex that match specific commands that we can treat case-insensitive and parts of the regex that match random payload that we must not modify.
This change cannot work one way or another, if you don't want to rewrite the entire project.

**Comment by Androbin** [comment]
Also btw. the `bytes` property is not used very much anyway. Really should be replaced with `match.group(0)`. So your change would actually have to be applied the the string that's fed into the regex.

**Pull request closed without merging**
